# .goreleaser.yaml
builds:
  - binary: picsort
    flags:
      - -tags=wayland
    ldflags:
      - -X github.com/coolapso/picsort/internal/ui.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/

archives:
  - files:
      - build/picsort.desktop
      - media/logo.png
aurs:
  - name: picsort-bin
    homepage: "https://github.com/coolapso/picsort"
    description: "PicSort is a simple tool to sort your pictures using only your keyboard"
    maintainers:
      - "coolapso <coolapso@coolapso.tech>"

    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/picsort-bin.git"
    skip_upload: auto

    package: |-
      # bin
      install -Dm755 picsort "$pkgdir/usr/bin/picsort"

      # Desktop
      install -Dm644 ./build/picsort.desktop "$pkgdir/usr/share/applications/picsort.desktop"

      # Icon
      install -Dm644 ./media/logo.png "$pkgdir/usr/share/pixmaps/picsort.png"

    # Git author used to commit to the repository.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

nfpms:
  - homepage: "https://picsort.cooolapso.sh"
    maintainer: "coolapso <coolapso@coolapso.tech>"
    description: "PicSort is a simple tool to sort your pictures using only your keyboard"
    license: "MIT"
    formats:
      - deb
      - rpm
    contents:
      - src: build/picsort.desktop
        dst: /usr/share/applications/picsort.desktop
      - src: media/logo.png
        dst: /usr/share/pixmaps/picsort.png

announce:
  discord:
    enabled: true
