version: '3'

tasks:
  run:
    cmds:
      - go run -tags wayland ./cmd
  live-run:
    cmds:
    - if [[ ! -d test/data ]]; then mkdir -p test/data; fi
    - air
  deploy-web:
    cmds:
      - wrangler --cwd web pages deploy --project-name picsort .
