name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  tests:
    uses: coolapso/picsort/.github/workflows/test.yaml@dev

  release:
    needs: tests
    # runining on the oldest possible lts to try to get most compatibility with users systems
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends bc clang lld libgl1-mesa-dev libwayland-dev libx11-dev libxkbcommon-dev xorg-dev xvfb language-pack-en
          echo "CC=clang" >> "$GITHUB_ENV"
          echo "CGO_LDFLAGS=-fuse-ld=lld" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.23"
      - uses: go-semantic-release/action@v1
        with:
          allow-initial-development-versions: true
          custom-arguments: "--commit-analyzer-opt patch_release_rules=fix,ref,build"
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
          DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
