name: Go

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends bc clang lld libgl1-mesa-dev libwayland-dev libx11-dev libxkbcommon-dev xorg-dev xvfb language-pack-en
          echo "CC=clang" >> "$GITHUB_ENV"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.23"

      - name: Install dependencies
        run: go get ./...

      - name: Check formating
        run: |
          changedFiles=$(go fmt ./...)
          if [[ -n $changedFiles ]]; then
            echo -e "Follwing files are not formated:\n${changedFiles}"
            exit 1
          fi

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          only-new-issues: true

      - name: test build
        run: go build -tags wayland -o megophone ./cmd
